apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-bookstore
  template:
    metadata:
      labels:
        app: php-bookstore
    spec:
      containers:
      - name: php-bookstore
        image: iyedhosni20/php-bookstore:latest  # Ensure this points to Docker Hub
        ports:
        - containerPort: 80
