apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-bookstore
  template:
    metadata:
      labels:
        app: php-bookstore
    spec:
      containers:
        - name: php-bookstore
          image: 192.168.1.71:5000/php-bookstore:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-bookstore-service
spec:
  selector:
    app: php-bookstore
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31800  # You can choose an available port here
